SpiNNakerManchester/SpiNNMachine

spinn_machine/machine.py, spinn_machine/spinnaker_link_data.py, spinn_machine/utilities/utilities.py
Fixes issues with SpiNNakerLink functionality
=> Fix spinnaker links

spinn_machine/machine.py, spinn_machine/multicast_routing_entry.py, unittests/test_multicast_routing_entry.py
supports a massive new way of working, which also supports allowing new mapping algorithms to be tied into the tool chain with minumal adjustments or caviats.
=> Mapping interface changes

spinn_machine/utilities/progress_bar.py
movement for SpinnMan branch changes.
=> movement of progress bar

spinn_machine/tags/abstract_tag.py, spinn_machine/tags/iptag.py, spinn_machine/tags/reverse_iptag.py
version of dynamic ports with few little changes
=> Dynamic ports v2

spinn_machine/tags/iptag.py, unittests/tag_tests/test_iptag.py, unittests/tag_tests/test_reverse_iptag.py
Adds the destination x and y coordinates of the Ethernet chip to the IPTag object
=> Fix board addresses

spinn_machine/link_data_objects/abstract_link_data.py
ALL Abstract cleanup pull requests must be done at the SAME time.
These include:
- SpiNNakerManchester/SpiNNMachine#35
- SpiNNakerManchester/SpiNNStorageHandlers#4
- SpiNNakerManchester/SpiNNMan#74
- SpiNNakerManchester/PACMAN#80
- SpiNNakerManchester/SpiNNFrontEndCommon#109
- SpiNNakerManchester/sPyNNaker#292
- SpiNNakerManchester/sPyNNakerExternalDevicesPlugin#49
=> Abstract cleanup

spinn_machine/__init__.py, spinn_machine/chip.py, spinn_machine/core_subsets.py, spinn_machine/link.py, spinn_machine/link_data_objects/__init__.py, spinn_machine/link_data_objects/fpga_link_data.py, spinn_machine/link_data_objects/spinnaker_link_data.py, spinn_machine/machine.py, spinn_machine/multicast_routing_entry.py, spinn_machine/processor.py, spinn_machine/router.py, spinn_machine/sdram.py, spinn_machine/tags/__init__.py, spinn_machine/tags/iptag.py, spinn_machine/tags/reverse_iptag.py, spinn_machine/virtual_machine.py, unittests/tag_tests/test_iptag.py, unittests/tag_tests/test_reverse_iptag.py, unittests/test_chip.py, unittests/test_link.py, unittests/test_machine.py, unittests/test_multicast_routing_entry.py, unittests/test_processor.py, unittests/test_router.py, unittests/test_sdram.py, unittests/test_spinnaker_triad_geometry.py, unittests/test_virtual_machine.py
This is about shortening the sometimes over-long full names of classes.
=> Shorten names

spinn_machine/chip.py, spinn_machine/machine.py, spinn_machine/router.py
Might as well expose the length if we expose the iterator.
=> Make SpiNNMachine more pythonic

spinn_machine/core_subset.py, spinn_machine/core_subsets.py
This is mainly about making the core subsets code a little bit more efficient by stopping it from making quite so many simple tuples when it doesn't need to. It also adjusts the core subset underneath to write the comparison code less twistedly (but with no performance difference).
=> Minor tweaking to CoreSubsets and CoreSubset

spinn_machine/core_subsets.py, unittests/test_coresubset.py, unittests/test_coresubsets.py
Fix for a bug in master (with tests to stop it happening again)
=> Add tests and fix len

spinn_machine/machine.py
makes the function actually work
=> fixes issue with get chips for board

spinn_machine/tags/iptag.py, spinn_machine/virtual_machine.py
Sometimes we return a boolean chosen in an `if`. Blugh.
=> Trivial simplification of boolean handling

spinn_machine/machine.py, spinn_machine/virtual_machine.py
adds some common coded magic numbers and uses them inside machine and virtual machine
=> magic numbers

spinn_machine/core_subsets.py, spinn_machine/machine.py, spinn_machine/router.py
improves on SDP by at least a factor of 2 for Ethernet connected chips and up to 22 times for none ethernet connected chips. 
links to other pull requests that need to be merged in at the same time
=> Speed up data in

.gitignore, .travis.yml, spinn_machine/chip.py, spinn_machine/core_subsets.py, spinn_machine/fixed_route_entry.py, spinn_machine/machine.py, spinn_machine/multicast_routing_entry.py, spinn_machine/processor.py, spinn_machine/router.py, spinn_machine/sdram.py, unittests/tag_tests/test_iptag.py, unittests/test_fixed_route_entry.py, unittests/test_multicast_routing_entry.py
Depends on SpiNNakerManchester/SpiNNUtils#50
=> Convert to also support Python 3

spinn_machine/machine.py, spinn_machine/spinnaker_triad_geometry.py, spinn_machine/virtual_machine.py, unittests/test_spinnaker_triad_geometry.py
Allows Ethernet chip to be disabled if there is a connectivity issue
=> fix multiboard ethernet

spinn_machine/core_subset.py, spinn_machine/core_subsets.py, unittests/test_coresubsets.py
Part of https://github.com/SpiNNakerManchester/spinnaker_tools/pull/75
But can be approved earlier
Support intersection of CoreSubsets
=> Dictionary for log messages

spinn_machine/processor.py, spinn_machine/virtual_machine.py
Can be done before PR that depend on this one.
=> Reuse processor Object when the same

spinn_machine/chip.py
Fix for https://github.com/SpiNNakerManchester/SpiNNMachine/issues/85
=> Only Chips with ip_address have tags by default.

spinn_machine/processor.py
How can you have a partial cpu cycle?
=> Cpu Cycles are int

spinn_machine/chip.py, spinn_machine/fixed_route_entry.py, spinn_machine/machine.py, spinn_machine/multicast_routing_entry.py, spinn_machine/router.py, spinn_machine/virtual_machine.py, unittests/tag_tests/test_iptag.py, unittests/tag_tests/test_reverse_iptag.py, unittests/test_chip.py, unittests/test_coresubset.py, unittests/test_coresubsets.py, unittests/test_import_all_test.py, unittests/test_machine.py, unittests/test_multicast_routing_entry.py, unittests/test_virtual_machine.py
https://www.python.org/dev/peps/pep-0328/#rationale-for-parentheses
=> Make import statements use PEP 328 better

spinn_machine/router.py
See SpiNNakerManchester/JavaSpiNNaker#87 for discussion.
Also added `Router.convert_spinnaker_route_to_routing_ids()` to reverse the mapping process, as part of putting the smarts in one place.
=> Teach Router about the real SpiNNaker limits.

spinn_machine/core_subsets.py, unittests/test_coresubsets.py
Required by https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/blob/master/spinn_front_end_common/interface/interface_functions/chip_provenance_updater.py
lines 45 and 46.
And who knows where else.
Only an error message so accepting OrderedDict format
=> added values() method to coresubsets as used in places

spinn_machine/machine.py, unittests/test_virtual_machine.py
Fixing point 1 of https://github.com/SpiNNakerManchester/SpiNNMachine/issues/75 to remove unnecessary use of lists
- edit to remove mixed directional notation as well (should either be North/South/East/West or Top/Bottom/Left/Right)
=> Update add_fpga_links to remove use of lists

spinn_machine/spinnaker_triad_geometry.py, unittests/test_spinnaker_triad_geometry.py
Fix for https://github.com/SpiNNakerManchester/SpiNNMachine/issues/96
=> handle machine that wrap in just one demension

spinn_machine/machine.py
Small change to support SpiNNakerManchester/PACMAN#188
=> Extractor2

setup.py, spinn_machine/chip.py, spinn_machine/core_subsets.py, spinn_machine/machine.py, spinn_machine/router.py
part of https://github.com/SpiNNakerManchester/SpiNNUtils/issues/75
=> Deprication Warnings

spinn_machine/sdram.py
better solution for 
https://github.com/SpiNNakerManchester/SpiNNMachine/pull/100
Required for 
https://github.com/SpiNNakerManchester/PACMAN/pull/194
https://github.com/SpiNNakerManchester/DataSpecification/pull/60
Can be done before
=> Sdram per timestep

spinn_machine/__init__.py, spinn_machine/full_wrap_machine.py, spinn_machine/horizontal_wrap_machine.py, spinn_machine/machine.py, spinn_machine/machine_factory.py, spinn_machine/no_wrap_machine.py, spinn_machine/vertical_wrap_machine.py, spinn_machine/virtual_machine.py
This function removes shared code from PACMAN and FEC.
=> Creating a create_one_board_machine function

spinn_machine/__init__.py, spinn_machine/full_wrap_machine.py, spinn_machine/horizontal_wrap_machine.py, spinn_machine/json_machine.py, spinn_machine/machine.py, spinn_machine/machine_factory.py, spinn_machine/no_wrap_machine.py, spinn_machine/router.py, spinn_machine/vertical_wrap_machine.py, spinn_machine/virtual_machine.py, unittests/test_json_machine.py, unittests/test_machine.py, unittests/test_virtual_machine.py
All PRs must be done at the same time.
https://github.com/SpiNNakerManchester/PACMAN/pull/222
https://github.com/SpiNNakerManchester/SpiNNMan/pull/161
https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/435
https://github.com/SpiNNakerManchester/sPyNNaker/pull/656
tested by 
https://github.com/SpiNNakerManchester/sPyNNaker8/pull/218
But that adds no new code
=> Wrapped machine

CITATION.cff, MANIFEST.in, pypi_to_import, setup.py, spinn_machine/_version.py
adds citation and manifest files. start point for further work on creating a doi for the tools
=> adds citation and manafest files

spinn_machine/machine_factory.py
Makes the error message local to the board and adds warning for repair
=> repair message fix

spinn_machine/machine_factory.py, unittests/test_virtual_machine.py
can be merged before dependencies
=> repair machine given list of removed chips

spinn_machine/multicast_routing_entry.py
Adds a spinnaker_route variable.
Does not break if merged before other PRs that depend on this.
=> Router json

spinn_machine/json_machine.py, spinn_machine/machine_factory.py, spinn_machine/router.py, unittests/test_chip.py, unittests/test_json_machine.py, unittests/test_machine.py, unittests/test_router.py, unittests/test_virtual_machine.py
We have too much unused info as it is.
Now there is one less.
Fix for 
https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/issues/419
Must be done at the same time as:
https://github.com/SpiNNakerManchester/PACMAN/pull/255
https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/477
https://github.com/SpiNNakerManchester/JavaSpiNNaker/pull/241
=> router clock speed was wrong and unused so hammer applied

setup.py, spinn_machine/chip.py, spinn_machine/core_subsets.py, spinn_machine/json_machine.py, spinn_machine/machine.py, spinn_machine/machine_factory.py, spinn_machine/router.py, spinn_machine/virtual_machine.py
https://github.com/SpiNNakerManchester/SpiNNUtils/issues/102
=> fixed incorrect import from collections.abc

spinn_machine/machine.py, spinn_machine/machine_factory.py, unittests/test_virtual_machine.py
this will help in 
https://github.com/SpiNNakerManchester/sPyNNaker8/issues/412
and solve
https://github.com/SpiNNakerManchester/SpiNNMachine/issues/132
=> better error message and reports all now for uni directional links

.travis.yml, setup.py, unittests/test_virtual_machine.py
Also run each version with best choice of Ubuntu distribution.
=> Add testing with Python 3.8

spinn_machine/machine_factory.py
needed for finding that blasted buggy board. 
put here coz determism is suffering
=> better detail for errror  message

spinn_machine/json_machine.py, spinn_machine/machine_factory.py, spinn_machine/virtual_machine.py
make use of https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/727
=> log warning to file

.github/workflows/python_actions.yml
=> Use right token for coveralls

spinn_machine/machine_factory.py, spinn_machine/spinn_machine.cfg, spinn_machine/virtual_machine.py, unittests/test_cfg_checker.py, unittests/test_json_machine.py, unittests/test_virtual_machine.py
Part of https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/792
=> Stop passing config values through the simulator

spinn_machine/chip.py, spinn_machine/json_machine.py, spinn_machine/virtual_machine.py
=> Pylint fixes

spinn_machine/chip.py, spinn_machine/core_subsets.py, spinn_machine/json_machine.py, spinn_machine/machine.py, spinn_machine/router.py
Similar to https://github.com/SpiNNakerManchester/PACMAN/pull/425
can be done independent
=> No need for "Ordered" dict

spinn_machine/chip.py
Store the virtual to physical map and enable lookups of the ID
=> store v to p map

spinn_machine/__init__.py, spinn_machine/chip.py, spinn_machine/core_subset.py, spinn_machine/core_subsets.py, spinn_machine/data/machine_data_view.py, spinn_machine/data/machine_data_writer.py, spinn_machine/exceptions.py, spinn_machine/fixed_route_entry.py, spinn_machine/ignores/ignore_chip.py, spinn_machine/ignores/ignore_core.py, spinn_machine/ignores/ignore_link.py, spinn_machine/json_machine.py, spinn_machine/link.py, spinn_machine/link_data_objects/abstract_link_data.py, spinn_machine/link_data_objects/fpga_link_data.py, spinn_machine/link_data_objects/spinnaker_link_data.py, spinn_machine/machine.py, spinn_machine/machine_factory.py, spinn_machine/multicast_routing_entry.py, spinn_machine/processor.py, spinn_machine/router.py, spinn_machine/sdram.py, spinn_machine/spinnaker_triad_geometry.py, spinn_machine/tags/abstract_tag.py, spinn_machine/tags/iptag.py, spinn_machine/tags/reverse_iptag.py, spinn_machine/virtual_machine.py, unittests/test_machine.py
This is a round of doc polishing and fixing of error messages and so on.
See SpiNNakerManchester/SpiNNUtils#223
See https://spinnmachine.readthedocs.io/en/doc-polish/
=> Doc polish

.github/workflows/python_actions.yml, .pylint_dict.txt, .pylintrc, spinn_machine/config_setup.py, spinn_machine/data/machine_data_view.py, spinn_machine/ignores/ignore_link.py, spinn_machine/json_machine.py, spinn_machine/machine.py, spinn_machine/machine_factory.py
See:
* https://github.com/SpiNNakerManchester/SupportScripts/pull/54
* https://github.com/SpiNNakerManchester/SpiNNUtils/pull/225
(The good thing is there doesn't appear to be many places that needed fixing.)
=> Enable spell checking of docstrings

setup.cfg, spinn_machine/_version.py
Part of https://github.com/SpiNNakerManchester/SpiNNUtils/pull/236
=> Version bump

.github/workflows/python_actions.yml
Use SupportScripts/.github/workflows/python_checks.yml
=> On workflow

spinn_machine/version/version_factory.py, unittests/data/test_data.py
fixes: https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/issues/1191
=> Better error on bad cfg

.github/workflows/python_actions.yml
Part of https://github.com/SpiNNakerManchester/sPyNNaker/pull/1455
=> coverage-package pylint-packages mypy-packages

.github/workflows/python_actions.yml, unittests/test_machine.py
similar to https://github.com/SpiNNakerManchester/PACMAN/pull/566
runs mypy on unittests
=> github action fixes

spinn_machine/version/version_48_chips.py, unittests/test_virtual_machine5.py, unittests/version/test_version248.py
fixes https://github.com/SpiNNakerManchester/SpiNNMachine/issues/255
=> None triad sizes

unittests/geometry.py, unittests/test_chip.py, unittests/test_coresubset.py, unittests/test_coresubsets.py, unittests/test_machine.py, unittests/test_using_virtual_machine.py, unittests/test_virtual_machine201.py, unittests/test_virtual_machine3.py, unittests/test_virtual_machine5.py
Typing test code and removing unused function in the tests.
No tests changed.
=> more unittest typing and cleanup

spinn_machine/data/machine_data_view.py
This reverts https://github.com/SpiNNakerManchester/SpiNNMachine/pull/286 
spinnman_integration_tests/test_job.py failed.
=> Revert "get_nearest_ethernet stricter"

spinn_machine/core_subsets.py, spinn_machine/data/machine_data_view.py, spinn_machine/data/machine_data_writer.py, spinn_machine/json_machine.py, spinn_machine/machine.py, spinn_machine/router.py, spinn_machine/spinnaker_triad_geometry.py, spinn_machine/version/abstract_version.py, spinn_machine/version/version_strings.py, unittests/test_doc_checker.py
depends on https://github.com/SpiNNakerManchester/SpiNNUtils/pull/327
includes https://github.com/SpiNNakerManchester/SpiNNMachine/pull/295
=> Docs fixes
