spinn_machine/machine.py

Allows you to run for an arbitrary number of timesteps, even when that means that recorded data will exceed the space on the machine. Even supports runtimes greater than originally allocated.

Auto pause and resume

---

spinn_machine/machine.py

fixed issue when using a spinnaker link 1 on a 4 chip board. Was a wee fix to how we get the ipaddress.
nothing else should be effected

fix for when using spinnaker link 1 on a 4 chip board.

---

spinn_machine/virtual_machine.py
unittests/test_virtual_machine.py

Found the issue causing the VM to appear to be the incorrect size: the VirtualMachine._configured_chips OrderedSet was being configured with the width and height swapped.
The Ethernet chips were being created correctly (according to the machine dimensions obtained from spalloc), and although they were added to the Machine._chips dictionary, it was never checked that these locations tallied with those in _configured_chips. Therefore, when the resource_tracker tried to grab these chips, it got nothing back.
There may be more we can do in terms of protecting against errors in both the VirtualMachine and Machine classes, and also the ResourceTracker, but for now a unit test has been included to prevent this specific error reoccurring.

Fix vm chip layout

---

spinn_machine/machine.py

creates a summary energy report. 
tied to 
PAC   https://github.com/SpiNNakerManchester/PACMAN/pull/98
FEC https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/155
spynnaker https://github.com/SpiNNakerManchester/sPyNNaker/pull/341
gfe https://github.com/SpiNNakerManchester/SpiNNakerGraphFrontEnd/pull/51

Chip power monitor

---

spinn_machine/__init__.py
spinn_machine/fixed_route_entry.py

allows the extra monitor core to use the fixed routes. Is tied to the following pull requests:
PAC, SpiNNakerManchester/PACMAN#127
fec , https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/216
spinn_man, https://github.com/SpiNNakerManchester/SpiNNMan/pull/98
GFE https://github.com/SpiNNakerManchester/SpiNNakerGraphFrontEnd/pull/68
need to all be merged at same time.

supports fixed route router

---

spinn_machine/fixed_route_entry.py
spinn_machine/processor.py

gives us a 5.4 times speed up on simple synfire chain. likely to give more for larger sims. 
depends upon the following prs:
Note that this work is not finished, but is stable. Future work will come which will increase this even further

Speed up data extractor

---

spinn_machine/chip.py
spinn_machine/core_subsets.py
spinn_machine/link.py
spinn_machine/link_data_objects/fpga_link_data.py
spinn_machine/link_data_objects/spinnaker_link_data.py
spinn_machine/machine.py
spinn_machine/multicast_routing_entry.py
spinn_machine/sdram.py
spinn_machine/spinnaker_triad_geometry.py
spinn_machine/tags/iptag.py
spinn_machine/tags/reverse_iptag.py
spinn_machine/virtual_machine.py

Remaining issues: some methods are too complicated and should be refactored for comprehensibility.
Relevant output from `propspector`:
```
spinn_machine/machine.py
Line: 361
pylint: too-many-statements / Too many statements (83/60) (col 4)
mccabe: MC0001 / Machine.add_fpga_links is too complex (21)
spinn_machine/virtual_machine.py
Line: 43
pylint: too-many-locals / Too many local variables (23/15) (col 4)
pylint: too-many-statements / Too many statements (86/60) (col 4)
mccabe: MC0001 / VirtualMachine.__init__ is too complex (33)
```

Simple issues found by pylint

---

spinn_machine/machine.py
unittests/test_machine.py
unittests/test_virtual_machine.py

This was causing me problems when running MCMC over more than 1 board via spalloc.
There should probably be a unit or integration test to check this works properly as well; happy to write it but will have to be next week now...

Fix for calling this function across multiple boards

---

spinn_machine/virtual_machine.py
unittests/test_virtual_machine.py

If an 8x8 machine is specified with wrap_arounds = True, a 64-chip machine is built.  This is disallowed by these changes, as such a machine cannot exist in reality.

Disallow Single Board Wraps

---

spinn_machine/utilities/ordered_set.py
spinn_machine/utilities/progress_bar.py

These classes are not used any more anywhere within our codebase (because they've been moved to SpiNNUtilites). We have no need to keep these stubs around.

Delete unused classes

---

spinn_machine/__init__.py
spinn_machine/chip.py
spinn_machine/core_subset.py
spinn_machine/core_subsets.py
spinn_machine/exceptions.py
spinn_machine/fixed_route_entry.py
spinn_machine/link.py
spinn_machine/link_data_objects/abstract_link_data.py
spinn_machine/link_data_objects/spinnaker_link_data.py
spinn_machine/machine.py
spinn_machine/multicast_routing_entry.py
spinn_machine/processor.py
spinn_machine/router.py
spinn_machine/spinnaker_triad_geometry.py
spinn_machine/tags/abstract_tag.py
spinn_machine/tags/iptag.py
spinn_machine/tags/reverse_iptag.py
spinn_machine/virtual_machine.py

Does a bunch of fixes in the documentation, using correct capitalisation for abbreviations and so on.
NB: <code>:py:class:\`~spinn_machine.Chip\`</code> formats as [`Chip`](/link-to-the-chip-docs) (except with the correct link, of course) so that's what I've converted internal links to use.

Documentation improvements

---

spinn_machine/machine.py
spinn_machine/virtual_machine.py
unittests/test_machine.py

Makes it possible to detect and map out chips that can't be used due to down links.

Unreachable chips

---

spinn_machine/virtual_machine.py

still works with our normal setups. but allows a vm which reflects the cores and routers of a spinnaker2

supports spinnaker_2 vm

---

spinn_machine/chip.py
spinn_machine/machine.py
spinn_machine/virtual_machine.py
unittests/test_chip.py
unittests/test_machine.py
unittests/test_virtual_machine.py

this came from reviewing the java, where the equiv removals should also be considerede

removes dead code from when we allocated reinjector as a monitor core

---

spinn_machine/full_wrap_machine.py
spinn_machine/horizontal_wrap_machine.py
spinn_machine/machine.py
spinn_machine/no_wrap_machine.py
spinn_machine/vertical_wrap_machine.py
spinn_machine/virtual_machine.py
unittests/test_virtual_machine.py

If a virtual machine is requested WITHOUT specifying n_cpus_per_chip  (or passing in None) a Machine is created with a split between 18 and 17 core chips as is typical in the 1,000,000 core machine.
Builds on: https://github.com/SpiNNakerManchester/SpiNNMachine/pull/124
So must be done AFTER that PR group.
Currently no matching PR to get the MaxMachineGenerators to use this but there probably should be one.

Accurate vm

---

.travis.yml
unittests/test_router.py

Upgrading Travis Ubuntu distribution to 18.04 (bionic) to help us with binaries that are close to the ITCM limit.
See https://github.com/orgs/SpiNNakerManchester/projects/32 for full list of PRs.

Upgrade travis dist to bionic

---

spinn_machine/chip.py
spinn_machine/machine_factory.py

Adds the concept of a "parent link" where this is the link to the parent chip in the tree used to send signals, which is rooted at the machine root chip.  This concept is then used (when present) to remove additional chips when a chip stops responding after boot.
Depends on SpiNNakerManchester/spinnaker_tools#135

Add link to info

---

doc/source/conf.py
spinn_machine/ignores/ignore_chip.py
spinn_machine/ignores/ignore_core.py
spinn_machine/ignores/ignore_link.py

These are the fixes to the documentation needed for SpiNNMachine to allow documentation to build without errors; these fixes are concentrated in the `spinn_machine.ignore` package. It also does some other basic fixes so that we don't have so many cut-n-paste jobs, and puts documentation on things where it was missing.

Fix the Python documentation

---

spinn_machine/multicast_routing_entry.py
unittests/test_multicast_routing_entry.py

Added a hash method to MulticastRoutingEntry so they could be added to sets.
Note: While in the end not used by HostBasedBitFieldRouterCompressor PR still a nice to have.

MulticastRoutingEntry.__hash.__

---

doc/doc_requirements.txt

The egg name fragment was wrong; it didn't match what SpiNNUtil's `setup.py` declared its name to be. This was making readthedocs fail.

It really helps a lot if you USE THE RIGHT URL

---

spinn_machine/machine.py
unittests/test_virtual_machine.py

Ideally the xy of a virtual chip should not be the same as the xy of a dead chip.
This adds a method on machine to giove you an unused xy

ask the machine for an unused xy

---

spinn_machine/full_wrap_machine.py
spinn_machine/horizontal_wrap_machine.py
spinn_machine/json_machine.py
spinn_machine/machine.py
spinn_machine/no_wrap_machine.py
spinn_machine/vertical_wrap_machine.py

machine._virtual_chips turned into an OrderedDict to make ii cheaper to check is chip xy is virtual
JsonMachine changed to use the virtual_chips property rather than underscore param
get_existing_xys_by_ethernet updated to check against virtual_chips if needed
get_chips_by_ethernet changed to work based off get_existing_xys_by_ethernet
(only known non test use of get_chips_by_ethernet should be using get_existing_xys_by_etherne anyway.

by_ethernet now excludes virtual chips

---

spinn_machine/machine.py
spinn_machine/router.py
spinn_machine/virtual_machine.py

This fixes a number of issues.
1. ROUTER_DEFAULT_AVAILABLE_ENTRIES = 1024   Which is WRONG!
2. Constant was not in Machine with all the other ones that  will change for Spinnaker2
3. Currently used value comes from the cfg but it does not make sense to let the user change that
Must be done at the same tine a:
https://github.com/SpiNNakerManchester/PACMAN/pull/377
https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/798

Router max entries is 1023

---

spinn_machine/machine.py
unittests/test_virtual_machine.py

Adds methods to machine to report the location of a chip.
Is used by other Prs But can be merged before them.
is tested by

Where is chip

---

spinn_machine/chip.py
spinn_machine/full_wrap_machine.py
spinn_machine/horizontal_wrap_machine.py
spinn_machine/ignores/ignore_core.py
spinn_machine/machine.py
spinn_machine/multicast_routing_entry.py
spinn_machine/no_wrap_machine.py
spinn_machine/processor.py
spinn_machine/spinn_machine.cfg
spinn_machine/vertical_wrap_machine.py
unittests/test_machine.py
unittests/test_multicast_routing_entry.py
unittests/test_virtual_machine.py

Adds a few useful things to the machine including:
1) A way to get concentric rings in a machine 
2) Ignore core ranges (useful to essentially remove a chip but still leave enough to route through it)
3) Not cause errors on duplicate links / processors, but instead just use sets to avoid issues
4) Remove an unused function that got a system processor.

Reduce overhead

---

spinn_machine/full_wrap_machine.py
spinn_machine/horizontal_wrap_machine.py
spinn_machine/json_machine.py
spinn_machine/machine.py
spinn_machine/no_wrap_machine.py
spinn_machine/vertical_wrap_machine.py
unittests/test_machine.py

Adds FPGAs and SpiNNaker links regardless of whether the links already exists.  This allows devices to be connected to these links even if other boards are, which is supported if the connection has a routing table in it.  Also adds the ability to specify the machine chip coordinates to which a device is connected, which can be easier for users.

Extdev fpgas

---

spinn_machine/fixed_route_entry.py
spinn_machine/multicast_routing_entry.py
spinn_machine/router.py
unittests/test_multicast_routing_entry.py

Sets really don't preserve order. They might pretend to in some circumstances, but they don't so we really shouldn't rely on it at all. Also, freeze key sets as we don't support modifying them anyway, and improve some doc comments

Tweaks to route classes

---

spinn_machine/chip.py

I'm not *sure* if this is necessary, but being able to use chips as keys simplifies a number of things and should reduce the amount of churn of tuples.
See:
* https://github.com/SpiNNakerManchester/SpiNNMan/pull/327
* https://github.com/SpiNNakerManchester/PACMAN/pull/513

Make Chip support equality/hashing so we can use directly in sets/dicts

---

spinn_machine/json_machine.py
spinn_machine/machine_factory.py
spinn_machine/router.py
spinn_machine/virtual_machine.py
unittests/test_chip.py
unittests/test_machine.py
unittests/test_router.py
unittests/test_virtual_machine.py

the Router emergency_routing_enabled is never used.
So this PR remove it.
tested by 
http://apollo.cs.man.ac.uk:8080/blue/organizations/jenkins/Integration%20Tests/detail/spin_1_or_2/2/pipeline

remove Emergency routing 

---

spinn_machine/machine.py

These constants are never used.
tested by
http://apollo.cs.man.ac.uk:8080/blue/organizations/jenkins/Integration%20Tests/detail/spin_1_or_2/2/pipeline

remove unused constants

---

spinn_machine/version/abstract_version.py
spinn_machine/version/version_3.py
spinn_machine/version/version_5.py
unittests/version/test_version3.py
unittests/version/test_version5.py

needed for https://github.com/SpiNNakerManchester/SpiNNMan/pull/353
Adds a few more properties to Version files.
But can be merged before

number and board_shape properties

---

spinn_machine/version/abstract_version.py
spinn_machine/version/version_factory.py
spinn_machine/virtual_machine.py

part of https://github.com/SpiNNakerManchester/SpiNNUtils/pull/244

Is config none

---

spinn_machine/chip.py
spinn_machine/json_machine.py
spinn_machine/version/abstract_version.py

fix or disable a  number of pylint warnings we have been ignoring

Pylint fixes

---

spinn_machine/chip.py
spinn_machine/machine_factory.py
unittests/test_chip.py

This PR.
1. Simplifies the String representation of a Chip but adds the the phyiscal monitor core.
2. Fixes tests due to 1
3. Uses the new string for the bad machine warnings
-including inlining the messages to make the code easier to read.
- fixes https://github.com/SpiNNakerManchester/SpiNNMachine/issues/228

Chip String fixes

---

.github/workflows/python_actions.yml

This and related PRs will now error if of the enabled pylint checks issue an message / error
related to: https://github.com/SpiNNakerManchester/SpiNNUtils/pull/261 (Which goes much farther)

error  on any pylint message

---

spinn_machine/virtual_machine.py
unittests/test_virtual_machine.py

fixes https://github.com/SpiNNakerManchester/SpiNNMachine/issues/227
the cfg "max_machine_core" was designed to cap the number of cores not fix it.
This pr move the getting of the max to 
_VirtualMachine
And also uses it as a max now and not a fixed amount.
Calling version.verify_size(height, width) also moved down into _VirtualMachine
must be done after
https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/1161
tested by:
http://apollo.cs.man.ac.uk:8080/blue/organizations/jenkins/Integration%20Tests/detail/cap_cores/1/pipeline/

vm core as min from version or cfg

---

spinn_machine/chip.py
unittests/test_chip.py
unittests/test_virtual_machine.py

fixes https://github.com/SpiNNakerManchester/SpiNNMachine/issues/242
removes all methods that expose the Processor class
Todo:
Move     CLOCK_SPEED = 200 * 1000 * 1000 and    DTCM_AVAILABLE = 2 ** 16 to version
remove the Processor class

only expose processor virtual ids

---

spinn_machine/chip.py
spinn_machine/json_machine.py
spinn_machine/machine.py
spinn_machine/version/abstract_version.py
spinn_machine/version/version_spin1.py
unittests/test_chip.py
unittests/test_json_machine.py
unittests/test_machine.py
unittests/test_virtual_machine.py
unittests/version/test_version3.py
unittests/version/test_version5.py

The names we have for processor types are reused with different meanings.
In Chip and processor "monitor" meant the scamp processor
Elsewhere "monitor" referred to the system cores.
These PRs suggest.
Rename Chip/Processor to
scamp - Processor 0 (in spin1)
placable - All others Ie where we can place stuff on
In PacmanDatView
system_cores  the cores used for inserted vertices
todo ?
The "monitor" label in the json we pass to the Java

processor renaming

---

spinn_machine/spinn_machine.cfg
spinn_machine/version/abstract_version.py
spinn_machine/version/version_201.py
spinn_machine/version/version_248.py
spinn_machine/version/version_3.py
spinn_machine/version/version_5.py
spinn_machine/version/version_factory.py
unittests/test_version_factory.py

part of https://github.com/SpiNNakerManchester/SpiNNUtils/pull/274
Version Factory will now raise a better error if there is conflicting info is found in the cfg.
To check if the info is conflicting Versions now have an eg and so hash function.

Cfg checker

---

setup.cfg
spinn_machine/machine.py
spinn_machine/version/abstract_version.py
spinn_machine/version/version_3.py
spinn_machine/version/version_5.py
spinn_machine/version/version_spin1.py
spinn_machine/version/version_spin2.py

Add energy monitoring calculations for SpiNNakerManchester/SpiNNFrontEndCommon#1226

Custom energy monitoring

---

.github/workflows/python_actions.yml
mypyd.bash
spinn_machine/chip.py
spinn_machine/core_subset.py
spinn_machine/core_subsets.py
spinn_machine/data/machine_data_view.py
spinn_machine/data/machine_data_writer.py
spinn_machine/exceptions.py
spinn_machine/frozen_core_subsets.py
spinn_machine/json_machine.py
spinn_machine/link_data_objects/spinnaker_link_data.py
spinn_machine/machine.py
spinn_machine/machine_factory.py
spinn_machine/router.py
spinn_machine/spinnaker_triad_geometry.py
spinn_machine/tags/abstract_tag.py
spinn_machine/tags/iptag.py
spinn_machine/tags/reverse_iptag.py
spinn_machine/version/abstract_version.py
spinn_machine/version/version_201.py
spinn_machine/version/version_248.py
spinn_machine/version/version_3.py
spinn_machine/version/version_48_chips.py
spinn_machine/version/version_5.py
spinn_machine/version/version_factory.py
spinn_machine/version/version_strings.py
spinn_machine/virtual_machine.py
unittests/tag_tests/test_iptag.py

Forces some checking for None higher up:
https://github.com/SpiNNakerManchester/SpiNNMan/pull/421
https://github.com/SpiNNakerManchester/PACMAN/pull/584
https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/1240
tested by:
https://github.com/SpiNNakerManchester/IntegrationTests/pull/299
Other repositories check with a matching branch name
https://github.com/SpiNNakerManchester/sPyNNaker/branches
https://github.com/SpiNNakerManchester/SpiNNakerGraphFrontEnd/branches
https://github.com/SpiNNakerManchester/MarkovChainMonteCarlo/branches
https://github.com/SpiNNakerManchester/microcircuit_model/branches
https://github.com/SpiNNakerManchester/SpiNNGym/branches

Typing of all SpinnMachine methods

---

spinn_machine/version/version_spin1.py
spinn_machine/version/version_spin2.py
unittests/version/test_version201.py
unittests/version/test_version248.py
unittests/version/test_version3.py
unittests/version/test_version5.py

The clock speeds claim to be in Hz, but are in MhZ.  Better if they are in hz (not that anything uses this yet - but it will soon!)

Fix the clock speeds
